[package]
name = "fqmul-test-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk" }
jolt-inlines-edwards-bls12.workspace = true

[lib]
test = false
doctest = false
bench = false

[[bin]]
name = "fqmul-test-guest"
path = "src/main.rs"
test = false
bench = false
