[package]
name = "fqmul-test-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []
field-inline = ["jolt/field-inline"]

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk" }
jolt-inlines-edwards-bls12 = { workspace = true, features = ["field-accel-bind"] }

[lib]
test = false
doctest = false
bench = false

[[bin]]
name = "fqmul-test-guest"
path = "src/main.rs"
test = false
bench = false

[dependencies.ark-ed-on-bls12-377]
version = "0.5.0"
default-features = false

[dependencies.ark-ff]
version = "0.5.0"
default-features = false
