[package]
name = "fqmul-test"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { workspace = true, features = ["host"] }
jolt-inlines-edwards-bls12 = { workspace = true, features = ["host"] }
tracing.workspace = true
tracing-subscriber.workspace = true
guest = { package = "fqmul-test-guest", path = "./guest" }
